### ISSUE TITLE
Docker login credentials are exposed in plain text within the agent environment tab

### ISSUE THREAD

**Issue by rmtobin** [buildkite-plugins/docker-login-buildkite-plugin#1]
Agent version v3.0-beta.39, plugin version v1.0.0

When viewing the "Environment" tab of a build step where I have used the Docker login plugin, the credentials used are shown in plaintext as part of the `BUILDKITE_PLUGINS` (see photo)

It would be better if any sensitive info could be scrubbed out to limit access to these credentials.

(This also may be an issue better suited for the agent or orchestrator, depending on how it is solved.)

<img width="1228" alt="buildkite_issue" src="https://user-images.githubusercontent.com/6315847/37004429-30d5a150-2085-11e8-93ff-b3be26fe14e0.png">

**Comment by lox** [comment]
Thanks for raising this @rmtobin. We need to have much clearer docs on this, having passwords leak into pipeline.yml and plugin config like this is no good. 

The best-practice way to approach this is to set `BUILDKITE_PLUGIN_DOCKER_LOGIN_PASSWORD` in your `env` hook, so that this value never makes it onto our servers or in your build output. I'll update the docs of this repo!

**Comment by lox** [comment]
Let me know if that answers your concern @rmtobin, unfortunately docker doesn't give us a lot of building blocks for secure credential management. Those credentials get stored on the host in base64 encode plaintext 😭

**Comment by lox** [comment]
We've updated our documentation on this plugin. Let us know if you have any more suggestions or concerns @rmtobin!

**Comment by rmtobin** [comment]
This is great, thanks @lox!
