### ISSUE TITLE
Suggestion: Remove credential in post-command hook

### ISSUE THREAD

**Issue by runlevel5** [buildkite-plugins/docker-login-buildkite-plugin#49]
The docker login would store credentials as clear text in `/var/lib/buildkite-agent/.docker/config.json` file. I think it is a good security practice to clean up this file once the command hook finishes. Thoughts? cc @toolmantim

**Comment by keithduncan** [comment]
Hi @runlevel5! This is kind of already done in the Elastic CI Stack which uses a [per-job Docker config directory](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/master/packer/linux/conf/buildkite-agent/hooks/pre-exit#L5-L8) and [cleans it up in a pre-exit hook](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/master/packer/linux/conf/buildkite-agent/hooks/pre-exit#L5-L8).

We could definitely add something similar to this plug-in for non-elastic ci stack use cases, though I think `pre-exit` would be preferable to `post-command` so that the artifact hooks have a chance to use these credentials if needed.
